### PR TITLE
Update to new v1 API endpoint

### PR DESCRIPTION
**Pull request by case**
We're moving to a versioned API endpoint.

### CODE REVIEW

**Comment by rakiru** [comment]
Thanks for this. :)

Did I miss a mailing list post, or has it not announced on there yet?

**Comment by case** [comment]
Haven't posted it to the list yet, but will later this week. Figured I'd send out some PRs first, and save folks a bit of work. ;)

**Comment by case** [comment]
Thanks for hacking with our API!

**Comment by rakiru** [comment]
Ah, I see. Much appreciated!

**Pull request merged**
