### PR TITLE
Remove client_id from source

### PR DESCRIPTION
**Pull request by case**
Due to API abuse, we're locking these down further. Details in our [API documentation](http://domainr.build/docs/authentication).

### CODE REVIEW

**Comment by gdude2002** [comment]
Hey there again, Case.

How are we supposed to deal with this, specifically? The docs say that client IDs are for high-traffic applications, and that one would have to contact you directly to get one - has the purpose changed somewhere along the line, is it not required, or.. I dunno. I'm kinda confused.

**Comment by case** [comment]
Hi there, apologies for the confusion!

We're asking folks to start using API keys via Mashape, as described in the API docs. Basically, the server operator can create a [Mashape account](https://www.mashape.com/nbio/domainr), then use the Domainr API via Mashape. Unfortunately there's been a fair amount of abusive API use, so we need to lock down the open-source client_ids.

**Comment by gdude2002** [comment]
It looks like the free tier is fine for our userbase.. Do we even need a client_id?

Also, are we going to have to rewrite for the new API, or..? It seems like a relatively major thing, but the plugin only has [about two users](https://ultros.io/metrics), so would need to weigh that into my dwindling amounts of free time as well

**Comment by case** [comment]
No need to re-write — the v1 API will continue to work indefinitely. It's a bit hidden in the documentation, but in the upper-right corner of domainr.build you can toggle back to the v1-versioned docs.

You can just pass in `?mashape-key={your-Mashape-API-key}` and it Should Just Work.

**Comment by gdude2002** [comment]
Alright, gotcha. I'll merge this in the interim, hopefully we'll get a look at this soon.

**Comment by case** [comment]
Much appreciated.

**Pull request merged**
